# Aula 5 — Pandas: seleção, filtros e criação de colunas

## Curso: Data Analytics e Visualização de Dados

Nesta aula, vamos trabalhar com o dataset **Students Performance**, uma base com informações sobre desempenho de estudantes em provas de matemática, leitura e escrita.

A proposta desta aula é sair do exemplo simples de vendas e usar uma base diferente para praticar operações fundamentais do Pandas.

---

## Objetivos da aula

Ao final desta aula, o aluno deverá ser capaz de:

- Carregar uma base de dados com Pandas;
- Entender a estrutura inicial de um DataFrame;
- Selecionar uma coluna;
- Selecionar múltiplas colunas;
- Usar `loc` e `iloc` de forma introdutória;
- Aplicar filtros simples;
- Aplicar filtros compostos com `&` e `|`;
- Criar novas colunas;
- Usar `apply()` com funções;
- Usar `lambda` em regras simples;
- Usar `map()` para substituir categorias;
- Usar `astype()` de forma introdutória.

# 1. Roteiro da aula


| Parte | Conteúdo |
|---|---|
| Apresentação do dataset | Entender a base Students Performance |
| Carregamento e primeira visualização  | `read_csv`, `head`, `shape`, `columns`, `info` |
| Padronização dos nomes das colunas | Ajustar nomes para facilitar o código |
| Seleção de colunas  | Uma coluna, várias colunas, Series x DataFrame |
| Introdução a `loc` e `iloc` | Seleção por nome e por posição |
| Filtros simples  | Filtros por texto e por valores numéricos |
| Filtros compostos  | Uso de `&`, `|` e parênteses |
| Criação de colunas | Média geral e novas variáveis |
| `apply`, `lambda`, `map` e `astype` | Transformações e classificações |
| Exercício guiado  | Prática com comandos essenciais |
| Desafio aplicado  | Perguntas analíticas |
| Fechamento | Síntese e conexão com a próxima aula |

# 2. Importando o Pandas

O Pandas é a biblioteca que usamos para trabalhar com dados em formato de tabela.

Por convenção, importamos o Pandas com o apelido `pd`.

In [1]:
import pandas as pd

# 3. Carregando o dataset

O arquivo enviado está com o nome:

```python
StudentsPerformance.csv
```

O arquivo está estruturado como um CSV, ou seja, como texto separado por vírgulas.

Por isso, vamos carregar com:

```python
pd.read_csv()
```

No Google Colab, faça upload do arquivo na lateral esquerda antes de executar a célula.

In [2]:
df = pd.read_csv("StudentsPerformance.csv")

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 4. Conhecendo a base de dados

Antes de fazer filtros ou criar colunas, precisamos entender a estrutura da base.

Vamos observar:

- primeiras linhas;
- quantidade de linhas e colunas;
- nomes das colunas;
- tipos de dados;
- resumo estatístico.

In [197]:
#primeiras linhas

In [102]:
#quantidade de linhas e colunas

(1000, 8)

O `shape` retorna a quantidade de linhas e colunas do DataFrame.

A estrutura do retorno é:

```python
(linhas, colunas)
```

In [198]:
#nomes das colunas

In [199]:
# tipos de dados

In [200]:
#resumo estatístico

# 5. Entendendo as colunas

A base possui informações sobre estudantes e suas notas.

| Coluna original | Significado |
|---|---|
| `gender` | gênero do estudante |
| `race/ethnicity` | grupo representado de forma anonimizada |
| `parental level of education` | escolaridade dos pais |
| `lunch` | tipo de almoço |
| `test preparation course` | se fez ou não curso preparatório |
| `math score` | nota de matemática |
| `reading score` | nota de leitura |
| `writing score` | nota de escrita |

Nesta aula, vamos usar essas colunas para praticar seleção, filtros e criação de novas variáveis.

# 6. Padronizando os nomes das colunas

Os nomes originais possuem espaços e caracteres como `/`.

Isso não impede a análise, mas pode dificultar a escrita do código.

Vamos padronizar os nomes para:

- letras minúsculas;
- sem espaços;
- com `_` no lugar dos espaços;
- com `_` no lugar de `/`.

In [201]:
# Padronizando os nomes das colunas

In [202]:
#Visualizando os nomes das colunas

Depois da padronização, os nomes ficam mais fáceis de usar:

| Nome original | Nome padronizado |
|---|---|
| `race/ethnicity` | `race_ethnicity` |
| `parental level of education` | `parental_level_of_education` |
| `test preparation course` | `test_preparation_course` |
| `math score` | `math_score` |
| `reading score` | `reading_score` |
| `writing score` | `writing_score` |

# 7. Selecionando uma coluna

Para selecionar uma única coluna, usamos:

```python
df["nome_da_coluna"]
```

Exemplo: selecionar apenas a coluna de nota de matemática.

In [203]:
#Selecionando 1 coluna

Quando selecionamos apenas uma coluna com um par de colchetes, o Pandas retorna uma **Series**.

Uma Series é como uma única coluna do DataFrame.

In [204]:
type(df["math_score"])

pandas.core.series.Series

# 8. Selecionando uma coluna como DataFrame

Se quisermos selecionar uma única coluna, mas manter o resultado como DataFrame, usamos dois pares de colchetes:

```python
df[["nome_da_coluna"]]
```

In [111]:
df[["math_score"]]

     math_score
0            72
1            69
2            90
3            47
4            76
..          ...
995          88
996          62
997          59
998          68
999          77

[1000 rows x 1 columns]

In [112]:
type(df[["math_score"]])

pandas.core.frame.DataFrame

## Diferença importante

| Código | Retorno |
|---|---|
| `df["math_score"]` | Series |
| `df[["math_score"]]` | DataFrame |

Quando uso um colchete, o Pandas me devolve uma coluna como Series. Quando uso dois colchetes, ele me devolve uma tabela, ou seja, um DataFrame.

# 9. Selecionando múltiplas colunas

Para selecionar várias colunas, usamos uma lista com os nomes das colunas.

Estrutura:

```python
df[["coluna1", "coluna2", "coluna3"]]
```

In [205]:
# Selecionando as colunas gender, math_score, reading_score e writing_score

Exemplo: selecionar apenas as colunas ligadas ao contexto do estudante.

In [114]:
df[["parental_level_of_education", "lunch", "test_preparation_course"]]

    parental_level_of_education         lunch test_preparation_course
0             bachelor's degree      standard                    none
1                  some college      standard               completed
2               master's degree      standard                    none
3            associate's degree  free/reduced                    none
4                  some college      standard                    none
..                          ...           ...                     ...
995             master's degree      standard               completed
996                 high school  free/reduced                    none
997                 high school  free/reduced               completed
998                some college      standard               completed
999                some college  free/reduced                    none

[1000 rows x 3 columns]

# 10. Introdução ao `loc`

O `loc` é usado para selecionar dados pelo **nome** da linha ou da coluna.

Estrutura geral:

```python
df.loc[linhas, colunas]
```

O `:` significa “todas as linhas” ou “todas as colunas”, dependendo da posição.

## Selecionando todas as linhas e algumas colunas com `loc`

In [115]:
df.loc[:, ["gender", "math_score", "reading_score"]]

     gender  math_score  reading_score
0    female          72             72
1    female          69             90
2    female          90             95
3      male          47             57
4      male          76             78
..      ...         ...            ...
995  female          88             99
996    male          62             55
997  female          59             71
998  female          68             78
999  female          77             86

[1000 rows x 3 columns]

Esse código significa:

> Selecione todas as linhas e apenas as colunas `gender`, `math_score` e `reading_score`.

## Selecionando as primeiras linhas e algumas colunas com `loc`

Como o índice começa em 0, podemos selecionar da linha 0 até a linha 4.

In [206]:
# Selecionando até a linha 4 e as colunas gender, math_score e reading_score

# 11. Introdução ao `iloc`

O `iloc` é usado para selecionar dados pela **posição numérica**.

Estrutura geral:

```python
df.iloc[linhas, colunas]
```

Aqui usamos posições, não nomes.

## Selecionando as 5 primeiras linhas e as 3 primeiras colunas

In [117]:
df.iloc[0:5, 0:3]

   gender race_ethnicity parental_level_of_education
0  female        group B           bachelor's degree
1  female        group C                some college
2  female        group B             master's degree
3    male        group A          associate's degree
4    male        group C                some college

Esse código significa:

> Pegue as linhas da posição 0 até antes da posição 5 e as colunas da posição 0 até antes da posição 3.

## Diferença entre `loc` e `iloc`

| Recurso | Seleciona por | Exemplo |
|---|---|---|
| `loc` | nome da linha/coluna | `df.loc[:, ["gender", "math_score"]]` |
| `iloc` | posição numérica | `df.iloc[0:5, 0:3]` |

Nesta aula, vamos usar `loc` e `iloc` apenas de forma introdutória. O aprofundamento pode aparecer mais adiante, em limpeza de dados e EDA.

# 12. Filtros simples

Filtros servem para selecionar apenas as linhas que atendem a uma condição.

Estrutura:

```python
df[condicao]
```

Exemplo:

```python
df[df["math_score"] >= 80]
```

A condição é avaliada linha por linha. O Pandas mantém apenas as linhas em que a condição é verdadeira.

## Estudantes com nota de matemática maior ou igual a 80

In [207]:
# codigo aqui

## Estudantes que fizeram o curso preparatório

In [208]:
# Código aqui

## Estudantes que não fizeram o curso preparatório

In [211]:
# codigo aqui

## Estudantes com tipo de almoço padrão

In [213]:
# Codigo

# 13. Salvando o resultado de um filtro

Podemos salvar um filtro em uma variável.

Isso deixa o código mais organizado quando queremos reutilizar o resultado.

In [216]:
# codigo aqui

In [217]:
# codigo aqui

# 14. Filtros compostos com E

Para combinar condições com ideia de **E**, usamos `&`.

Exemplo:

> Estudantes que fizeram curso preparatório E tiveram nota de matemática maior ou igual a 80.

Cada condição precisa ficar entre parênteses.

In [218]:
# Codigo aqui

## Outro exemplo com E

Estudantes do gênero feminino com nota de escrita maior ou igual a 90.

In [219]:
# Codigo aqui

# 15. Filtros compostos com OU

Para combinar condições com ideia de **OU**, usamos `|`.

Exemplo:

> Estudantes com nota de leitura maior ou igual a 90 OU nota de escrita maior ou igual a 90.

In [220]:
# Codigo aqui

## Outro exemplo com OU

Estudantes do grupo A ou do grupo B.

In [221]:
# Codigo aqui

# 16. Erro comum: esquecer os parênteses

No Pandas, quando usamos `&` ou `|`, cada condição precisa estar entre parênteses.

Forma correta:

```python
df[(condicao1) & (condicao2)]
```

Forma incorreta:

```python
df[condicao1 & condicao2]
```

Esse é um dos erros mais comuns para quem está começando.

# 17. Criando uma nova coluna com cálculo

Agora vamos criar uma nova coluna chamada `media_geral`.

Ela será a média das três notas:

- matemática;
- leitura;
- escrita.

In [223]:
# codigo aqui

# 18. Criando uma coluna com diferença entre notas

Também podemos criar uma coluna que representa a diferença entre duas notas.

Exemplo:

```python
math_score - reading_score
```

In [224]:
#Codigo aqui

# 19. Criando coluna com a maior nota do estudante

Para calcular a maior nota entre matemática, leitura e escrita, usamos `.max(axis=1)`.

O `axis=1` indica que o cálculo deve ser feito linha por linha.

In [225]:
# Codigo aqui

# 20. Criando coluna com a menor nota do estudante

Da mesma forma, podemos usar `.min(axis=1)` para calcular a menor nota do estudante.

In [226]:
#Codigo aqui

# 21. Usando `apply()` com função

O `apply()` permite aplicar uma função a cada valor de uma coluna.

Vamos criar uma coluna chamada `situacao`.

Regra:

- média geral maior ou igual a 60: `Aprovado`;
- média geral menor que 60: `Reprovado`.

In [227]:
# Definindo a funcao

In [230]:
# visualizando as primeiras linhas do df

In [229]:
# Codigo aqui

## Como ler esse código?

```python
df["media_geral"].apply(definir_situacao)
```

O Pandas pega cada valor da coluna `media_geral`, envia para a função `definir_situacao` e devolve o resultado para a nova coluna.

# 22. Usando `lambda`

O `lambda` é uma função simples, escrita em uma única linha.

Ele é útil quando a regra é curta.

A regra de aprovado ou reprovado também pode ser escrita com `lambda`.

In [232]:
# Usando o lambda

## Quando usar `lambda`?

Use `lambda` quando a regra for simples.

Exemplo adequado:

```python
lambda media: "Aprovado" if media >= 60 else "Reprovado"
```

Quando a regra tiver muitas condições, prefira criar uma função com `def`, porque fica mais fácil de ler.

# 23. Classificação de desempenho com função

Agora vamos criar uma classificação com três níveis.

Regra:

- média maior ou igual a 80: `Alto desempenho`;
- média maior ou igual a 60: `Desempenho médio`;
- média abaixo de 60: `Baixo desempenho`.

Como temos mais de uma condição, a função com `def` é mais didática.

In [234]:
# definindo a função

In [233]:
# aplicando a função

# 24. Usando `map()` para substituir categorias

O `map()` é muito útil quando queremos substituir valores usando um dicionário.

Ele é ideal para traduzir categorias ou criar nomes mais amigáveis.

## Traduzindo a coluna `gender`

In [236]:
#codigo aqui

## Traduzindo a coluna `lunch`

In [240]:
# Codigo aqui

# 25. Diferença entre `apply()`, `lambda` e `map()`

| Recurso | Melhor uso | Exemplo |
|---|---|---|
| `apply()` | Aplicar uma função em uma coluna | classificar média |
| `lambda` | Criar uma função curta em uma linha | aprovado/reprovado |
| `map()` | Substituir valores com dicionário dentro de uma coluna| traduzir categorias |

## Resumo

- Use `map()` para substituições diretas;
- Use `apply()` quando houver uma regra ou função;
- Use `lambda` quando a regra for simples e curta.

# 26. Introdução ao `astype()`

O `astype()` serve para converter o tipo de uma coluna.

Antes de converter, vamos verificar os tipos com `info()`.

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
 8   media_geral                  1000 non-null   float64
 9   diferenca_math_reading       1000 non-null   int64
 10  nota_maxima                  1000 non-null   int64
 11  nota_minima                  1000 non-null   int64
 12  situacao                     1000 non-null   object
 13  situacao_lambda              1000 non-null   object
 14  classificacao_desempenho     1000 non-null   object
 15  genero_pt                    1000 non-null   object
 16  curso_preparatorio_pt        1000 non-null   object
 17  tipo_almoco_pt               1000 non-null   object
dtypes: float64(1), int64(6), object(11)
memory usage: 140.8+ KB

As notas aparecem como números.

Podemos converter uma coluna numérica inteira para número decimal usando `astype(float)`.

In [241]:
# codigo aqui

Também podemos converter colunas de texto para o tipo `category`.

Isso pode ser útil para colunas com poucos valores repetidos, como gênero, almoço e curso preparatório.Ele ajuda o Pandas a entender melhor a natureza da coluna e pode economizar memória quando existem muitos valores repetidos.

In [242]:
# gender, lunch , test_preparation_courses

# 27. Perguntas analíticas com filtros

Agora vamos responder algumas perguntas usando os comandos aprendidos.

## Pergunta 1

Quais estudantes tiveram média geral maior ou igual a 80?

In [5]:
#Codigo aqui
df.columns = df.columns.str.replace(" ", "_").str.replace("/", "_")

df["media_geral"] = (df["math_score"] + df["writing_score"] + df["reading_score"]) / 3
print(df[(df["media_geral"] >= 80)])

     gender race_ethnicity parental_level_of_education         lunch  \
1    female        group C                some college      standard
2    female        group B             master's degree      standard
6    female        group B                some college      standard
16     male        group C                 high school      standard
34     male        group E                some college      standard
..      ...            ...                         ...           ...
982    male        group B            some high school      standard
983  female        group A                some college      standard
990    male        group E                 high school  free/reduced
995  female        group E             master's degree      standard
999  female        group D                some college  free/reduced

    test_preparation_course  math_score  reading_score  writing_score  \
1                 completed          69             90             88
2                      none          90             95             93
6                 completed          88             95             92
16                     none          88             89             86
34                     none          97             87             82
..                      ...         ...            ...            ...
982               completed          79             85             86
983               completed          78             87             91
990               completed          86             81             75
995               completed          88             99             95
999                    none          77             86             86

     media_geral
1      82.333333
2      92.666667
6      91.666667
16     87.666667
34     88.666667
..           ...
982    83.333333
983    85.333333
990    80.666667
995    94.000000
999    83.000000

[198 rows x 9 columns]

## Pergunta 2

Quais estudantes fizeram curso preparatório e tiveram média geral maior ou igual a 80?

In [6]:
# Codigo aqui
print(df[(df["media_geral"] >= 80) & (df["test_preparation_course"] == "completed")])

     gender race_ethnicity parental_level_of_education         lunch  \
1    female        group C                some college      standard
6    female        group B                some college      standard
35     male        group E          associate's degree      standard
38   female        group D          associate's degree  free/reduced
49     male        group C                 high school      standard
..      ...            ...                         ...           ...
938    male        group D                some college      standard
982    male        group B            some high school      standard
983  female        group A                some college      standard
990    male        group E                 high school  free/reduced
995  female        group E             master's degree      standard

    test_preparation_course  math_score  reading_score  writing_score  \
1                 completed          69             90             88
6                 completed          88             95             92
35                completed          81             81             79
38                completed          75             90             88
49                completed          82             84             82
..                      ...         ...            ...            ...
938               completed          85             81             85
982               completed          79             85             86
983               completed          78             87             91
990               completed          86             81             75
995               completed          88             99             95

     media_geral
1      82.333333
6      91.666667
35     80.333333
38     84.333333
49     82.666667
..           ...
938    83.666667
982    83.333333
983    85.333333
990    80.666667
995    94.000000

[107 rows x 9 columns]

## Pergunta 3

Quais estudantes não fizeram curso preparatório e foram reprovados?

In [7]:
# Codigo aqui
def situacao_estudante(media):
     if media >= 60:
         return "Aprovado"
     else:
         return "Reprovado"

df["situacao"] = df["media_geral"].apply(situacao_estudante)

print(df[(df["test_preparation_course"] == "none") & (df["situacao"] == "Reprovado")])

     gender race_ethnicity parental_level_of_education         lunch  \
3      male        group A          associate's degree  free/reduced
7      male        group B                some college  free/reduced
9    female        group B                 high school  free/reduced
10     male        group C          associate's degree      standard
11     male        group D          associate's degree      standard
..      ...            ...                         ...           ...
980  female        group B                 high school  free/reduced
985    male        group A                 high school      standard
986  female        group C          associate's degree      standard
988  female        group A            some high school  free/reduced
996    male        group C                 high school  free/reduced

    test_preparation_course  math_score  reading_score  writing_score  \
3                      none          47             57             44
7                      none          40             43             39
9                      none          38             60             50
10                     none          58             54             52
11                     none          40             52             43
..                      ...         ...            ...            ...
980                    none           8             24             23
985                    none          57             51             54
986                    none          40             59             51
988                    none          44             45             45
996                    none          62             55             55

     media_geral   situacao
3      49.333333  Reprovado
7      40.666667  Reprovado
9      49.333333  Reprovado
10     54.666667  Reprovado
11     45.000000  Reprovado
..           ...        ...
980    18.333333  Reprovado
985    54.000000  Reprovado
986    50.000000  Reprovado
988    44.666667  Reprovado
996    57.333333  Reprovado

[225 rows x 10 columns]

## Pergunta 4

Quais estudantes tiveram nota de matemática menor que 50, mas nota de leitura maior ou igual a 70?

In [8]:
#codigo aqui
print(df[(df["math_score"] < 50) & (df["reading_score"] >= 70)])

     gender race_ethnicity parental_level_of_education         lunch  \
371  female        group C                some college  free/reduced

    test_preparation_course  math_score  reading_score  writing_score  \
371               completed          45             73             70

     media_geral  situacao
371    62.666667  Aprovado

# 28. Exercício guiado

Agora é a vez dos alunos praticarem.

## Parte 1 — Seleção de colunas

1. Selecione apenas a coluna `math_score`.
2. Selecione as colunas `gender`, `math_score` e `reading_score`.
3. Selecione as colunas `parental_level_of_education` e `test_preparation_course`.
4. Selecione as colunas `math_score`, `reading_score` e `writing_score`.

In [ ]:
# Exercício 1
# Selecione apenas a coluna math_score

print(df["math_score"])

In [ ]:
# Exercício 2
# Selecione as colunas gender, math_score e reading_score

print(df[["gender", "math_score", "reading_score"]])

In [ ]:
# Exercício 3
# Selecione as colunas parental_level_of_education e test_preparation_course

print(df[["parental_level_of_education", "reading_score"]])

In [ ]:
# Exercício 4
# Selecione as colunas math_score, reading_score e writing_score

print(df[["math_score", "reading_score", "writing_score"]])

## Parte 2 — `loc` e `iloc`

5. Use `loc` para selecionar todas as linhas e apenas as colunas `gender` e `math_score`.
6. Use `loc` para selecionar as linhas de 0 a 6 e as colunas `gender`, `math_score` e `reading_score`.
7. Use `iloc` para selecionar as 5 primeiras linhas e as 3 primeiras colunas.
8. Use `iloc` para selecionar as 10 primeiras linhas e as 2 primeiras colunas.

In [ ]:
# Exercício 5
# Use loc para selecionar todas as linhas e as colunas gender e math_score

print(df.loc[:, ["gender", "math_score"]])

In [ ]:
# Exercício 6
# Use loc para selecionar as linhas 0 a 6 e as colunas gender, math_score e reading_score

print(df.loc[0:6, ["gender", "math_score", "reading_score"]])

In [ ]:
# Exercício 7
# Use iloc para selecionar as 5 primeiras linhas e as 3 primeiras colunas

print(df.iloc[0:5, 0:3])

In [ ]:
# Exercício 8
# Use iloc para selecionar as 10 primeiras linhas e as 2 primeiras colunas

print(df.iloc[0:10, 0:2])

## Parte 3 — Filtros simples

9. Filtre estudantes com `math_score` maior ou igual a 70.
10. Filtre estudantes que fizeram o curso preparatório.
11. Filtre estudantes com `writing_score` menor que 60.
12. Filtre estudantes com tipo de almoço `free/reduced`.

In [ ]:
# Exercício 9
# Estudantes com math_score >= 70

print(df[(df["math_score"] >= 70)])

In [ ]:
# Exercício 10
# Estudantes que fizeram o curso preparatório

print(df[(df["test_preparation_course"] == "completed")])

In [ ]:
# Exercício 11
# Estudantes com writing_score < 60

print(df[(df["writing_score"] < 60)])

In [ ]:
# Exercício 12
# Estudantes com lunch == free/reduced

print(df[(df["lunch"] == "free/reduced")])

## Parte 4 — Filtros compostos

13. Filtre estudantes que fizeram o curso preparatório e tiveram `math_score` maior ou igual a 80.
14. Filtre estudantes com `reading_score` maior ou igual a 90 ou `writing_score` maior ou igual a 90.
15. Filtre estudantes do gênero feminino com média geral maior ou igual a 80.
16. Filtre estudantes que não fizeram curso preparatório e foram reprovados.

In [ ]:
# Exercício 13
# Curso preparatório completed E math_score >= 80

print(df[(df["test_preparation_course"] == "completed") & (df["math_score"] >= 80)])

In [ ]:
# Exercício 14
# reading_score >= 90 OU writing_score >= 90

print(df[(df["reading_score"] >= 90) | (df["writing_score"] >= 90)])

In [ ]:
# Exercício 15
# gender == female E media_geral >= 80
df["media_geral"] = (df["math_score"] + df["writing_score"] + df["reading_score"]) / 3

print(df[(df["gender"] == "female") & (df["media_geral"] >= 80)])

In [ ]:
# Exercício 16
# test_preparation_course == none E situacao == Reprovado

print(df[(df["test_preparation_course"] == "none") & (df["situacao"] == "Reprovado")])

## Parte 5 — Criação de colunas

17. Crie uma coluna chamada `amplitude_notas`, calculando a diferença entre a maior e a menor nota do estudante.
18. Crie uma coluna chamada `perfil_matematica`, classificando:
    - `Forte em matemática` para nota de matemática maior ou igual a 80;
    - `Precisa melhorar em matemática` para os demais casos.
19. Crie uma coluna chamada `curso_preparatorio_pt`, traduzindo a coluna test_preparation_course com map():
    - `completed` → Fez o curso
    - `none` → Não fez o curso
20. Converta a coluna `reading_score` para `float` usando `astype()`.

In [ ]:
# Exercício 17
# Crie a coluna amplitude_notas 

df["amplitude_notas"] = df[["math_score", "reading_score", "writing_score"]].max(axis=1) - df[["math_score", "reading_score", "writing_score"]].min(axis=1)

In [ ]:
# Exercício 18
# Crie a coluna perfil_matematica usando apply ou lambda

def perfil_mat(nota):
    if nota >= 80:
        return "Forte em matemática"
    else:
        return "Precisa melhorar"

df["perfil_matematica"] = df["math_score"].apply(perfil_mat)

In [ ]:
# Exercício 19
# Crie a coluna curso_preparatorio_pt usando map

df["curso_preparatorio_pt"] = df["test_preparation_course"].map({
    "none": "nenhum",
    "completed": "concluído"
})

In [ ]:
# Exercício 20
# Converta reading_score para float usando astype

df["reading_score"] = df["reading_score"].astype(float)

# 29. Desafio aplicado

A escola quer identificar estudantes que merecem atenção e estudantes com alto desempenho.

Responda usando Pandas:

1. Quantos estudantes tiveram alto desempenho?
2. Quais estudantes fizeram curso preparatório e tiveram média geral acima de 85?
3. Quais estudantes não fizeram curso preparatório e tiveram baixo desempenho?
4. Existe algum estudante com nota de matemática menor que 40 e leitura maior que 70?
5. Crie uma coluna chamada `perfil_final`, classificando:
   - `Excelente`: média geral maior ou igual a 85;
   - `Regular`: média geral maior ou igual a 60;
   - `Atenção`: média geral menor que 60.

Depois, escreva uma frase interpretando um dos resultados.

In [ ]:
# Desafio 1
# Quantos estudantes tiveram alto desempenho?

def desempenho_estudantes(media):
    if media >= 85:
        return "Alto desempenho"
    elif media >= 60:
        return "Médio desempenho"
    else: 
        return "Baixo desempenho"
    
df["desempenho"] = df["media_geral"].apply(desempenho_estudantes)

print(df[(df["desempenho"]) == "Alto desempenho"]["desempenho"])

In [ ]:
# Desafio 2
# Estudantes que fizeram curso preparatório e tiveram média geral acima de 85

print(df[(df["test_preparation_course"] == "completed") & (df["media_geral"] >= 85)])

In [ ]:
# Desafio 3
# Estudantes que não fizeram curso preparatório e tiveram baixo desempenho

print(df[(df["test_preparation_course"] == "none") & (df["desempenho"] == "Baixo desempenho")])

In [ ]:
# Desafio 4
# Matemática menor que 40 e leitura maior que 70

print(df[(df["math_score"] < 40) & (df["reading_score"] > 70)])

In [171]:
# Desafio 5
# Criar coluna perfil_final

#  Fechamento da aula

Nesta aula, aprendemos a manipular uma base de dados com Pandas usando operações fundamentais para análise.

## Principais comandos vistos

| Conceito | Exemplo |
|---|---|
| Selecionar uma coluna | `df["math_score"]` |
| Selecionar várias colunas | `df[["gender", "math_score"]]` |
| Selecionar por nome | `df.loc[:, ["gender", "math_score"]]` |
| Selecionar por posição | `df.iloc[0:5, 0:3]` |
| Filtro simples | `df[df["math_score"] >= 80]` |
| Filtro com E | `df[(cond1) & (cond2)]` |
| Filtro com OU | `df[(cond1) \| (cond2)]` |
| Criar coluna | `df["media_geral"] = ...` |
| Aplicar função | `df["media_geral"].apply(funcao)` |
| Função curta | `lambda x: ...` |
| Substituir categorias | `map()` |
| Converter tipo | `astype()` |

## Conexão com a próxima aula

Na próxima aula, vamos trabalhar com **limpeza de dados com Pandas**.

A ideia será tratar problemas comuns em bases reais, como:

- valores nulos;
- duplicatas;
- tipos de dados incorretos;
- textos fora de padrão;
- renomeação de colunas;
- conversão de datas.